baseURL  =  "https://blog-chenplus.vercel.app/"
languageCode = "zh-CN"
# DefaultContentLanguage = "zh-CN"
title  =  "è€é™³ç½‘å¿—"
subtitle = "æ‰‹å¸³ &ãƒãƒ¼ãƒˆğŸ“˜"

theme  =  "hello-friend"
summaryLength = 140
hasCJKLanguage = true
# æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡ç”¨äºåˆ†é¡µ
paginate =  6
# rss è¾“å‡ºæ•°é‡
rssLimit = 5


[menu]
  [[menu.main]]
  name="å½’æ¡£"
  url="/archives/"
  weight="1"
  [[menu.main]]
  name="å“”å“”"
  url="/bb/"
  weight="2"
  [[menu.main]]
  name="å…³äº"
  url="/about/"
  weight="3"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  logoText = "hello friend"

  MenuMore = "æ›´å¤š"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "é˜…è¯»å…¨æ–‡"

  EditPath = 'https://github.com/OldChenGit/Blog/edit/master/content'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["Atom", "HTML","JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.twikoo]
	enable = true